region              = "eu-west-1"
az                  = ["eu-west-1a", "eu-west-1b"]
cidr                = "172.25.0.0/16"
private_subnet_cidr = ["172.25.52.0/24", "172.25.54.0/24"]
public_subnet_cidr  = ["172.25.62.0/24", "172.25.64.0/24"]
environment         = "network"
project_name        = "cloudTalents"
ram_name            = "vpc-subnets"
vpc_name            = "vpc-network"
private_subnet_name = ["pvt-sub-0", "pvt-sub-1"]
public_subnet_name  = ["pub-sub-0", "pub-sub-1"]
igw_name            = "igw"
private_rt_name     = ["pvt-rt-0", "pvt-rt-1"]
public_rt_name      = ["pub-rt-0", "pub-rt-1"]